pipeline {
    agent any
    
    stages{
        stage('CODE ANALYSIS-SONARQUBE') {
           steps {
               sh 'echo sonar analysis completed'
               sh 'cd webapp && sudo docker run  --rm -e SONAR_HOST_URL="http://13.232.171.150:9000" -e SONAR_LOGIN="sqp_d90742c8d3ee89475152104b4ce2fafa3bc09701"  -v ".:/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=lms'
             }
          }
    }
}
