pipeline {
    agent any
     
    
    stages{
        stage('build Analysis') {
           steps {
               sh 'cd webapp && npm install && npm run build'
              
             }
          }
        stage('Releasin Artifact in Nexus'){
             steps {
                script{
                    echo "Releasing"
                    def packageJSON = readJSON file: 'webapp/package.json'
                    def packageJSONVersion = packageJSON.version
                    echo "{packageJSONVersion}"
                    sh "zip webapp/dist-${packageJSONVersion}.zip -r webapp/dist"
                    sh "curl -v -u admin:password --upload-file webapp/dist-${packageJSONVersion}.zip http://65.2.30.94:8081/repository/lms/"
                    }
        }
        }
            stage('Deploying LMS'){
             steps {
                script{
                    echo "Deploy LMS"
                    def packageJSON = readJSON file: 'webapp/package.json'
                    def packageJSONVersion = packageJSON.version
                    echo "{packageJSONVersion}"
                    sh " curl -u admin:password -X GET http://65.2.30.94:8081/repository/lms/dist-${packageJSONVersion}.zip --output dist-${packageJSONVersion}.zip"
                    sh 'sudo rm -rf /var/www/html/*'
                    sh "sudo unzip -o dist-${packageJSONVersion}.zip"
                    sh "sudo cp -r webapp/dist/* /var/www/html"
                    }
        }
        }
    }
}
