pipeline {
    agent {
    node{
	 label 'docker'
	}
    }
    environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhubuser')
     registry = "gruchi16/frontend-lms"
        registryCredential = 'dockerhubuser'
    }
    stages{
	stage('CODE ANALYSIS-SONARQUBE') {
           steps {
               sh 'echo sonar analysis completed'
               sh 'cd webapp && sudo docker run  --rm -e SONAR_HOST_URL="http://13.233.83.91:9000" -e SONAR_LOGIN="sqp_030d76b55bf8033b3e17149a15c51edd2d3aa72c"  -v ".:/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=lms'
             }
          }
       
        stage('Docker Build') {
            steps {
                sh 'cd webapp && docker build -t gruchi16/frontend-lms .'
             }
          }
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
          }
        stage('Docker Push') {
            steps {
                sh 'docker push gruchi16/frontend-lms'
            }
          }
        stage('Remove old images') {
            steps {
                sh 'docker rmi -f gruchi16/frontend-lms'
              }
          }
        stage('Docker run'){
            steps{
                sh 'docker container run -dt --name web -p 80:80 gruchi16/frontend-lms'
            }
         }
	}
}
