pipeline {
    agent {
    node {
        label 'docker'
         }
        }
    environment {
    dockerhub=credentials('dockerhubuser')
    }
    stages{
        stage('Docker Build') {
            steps {
                sh 'cd api && docker build -t gruchi16/backend-lms .'
             }
          }
        stage('Docker Login') {
            steps {
                sh 'echo $dockerhubuser_PSW | docker login -u $dockerhubuser_USR --password-stdin'
            }
          }
        stage('Docker Push') {
            steps {
                sh 'docker push gruchi16/backend-lms'
		sh 'docker container run -dt --name api -p 3000:3000 gruchi16/backend-lms'
            }
          }
        stage('Remove old docker images') {
            steps {
                sh 'docker rmi -f gruchi16/backend-lms'
              }
          }
        stage('creating database container') {
            steps {
                sh 'docker container rm --force lmsdb'
                sh 'docker run -d -p 5432:5432 --network lmsnetwork -e POSTGRES_PASSWORD=password --name lmsdb postgres'
                }
           }
        stage('Running the docker container') {
            steps {
                sh 'docker container rm --force api'
                sh 'docker run -d -p 3000:3000 --network lmsnetwork -e DATABASE_URL=postgresql://postgres:password@lmsdb:5432/postgres --name api -e PORT=3000 -e MODE=local gruchi16/backend-lms'
                }
              }
        }
  }
